#!/usr/bin/env bash

set -euo pipefail
set -x

export PATH=/usr/bin:/bin:/sbin

mount -t proc none /proc
mount -t sysfs none /sys
hostname -F /hostname

if ! mount -t 9p -o trans=virtio host /host; then
    echo 'no host share accessible, it can be added to QEMU using:'
    echo '-virtfs local,path=$(pwd)/,mount_tag=host,security_model=mapped,readonly=off'
fi
if ifconfig -a | grep -q eth0; then
    ifconfig eth0 up
    ifconfig eth0 10.0.2.15 netmask 255.255.255.0 broadcast 10.0.2.255
    route add default gw 10.0.2.2
else
    echo 'no network device'
fi

if [ $# -ge 1 ]; then
    if ! "$@"; then
        echo "command failed: $*"
        sync
        echo c > /proc/sysrq-trigger
    fi
else
    setsid -c /bin/bash -l || true
fi

sync
echo o > /proc/sysrq-trigger
sleep 10
