#!/usr/bin/env bash

set -euo pipefail
set -x

export PATH=/usr/bin:/bin:/sbin

mount -t proc none /proc
mount -t sysfs none /sys
mkdir /dev/pts
mount devpts /dev/pts -t devpts
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

hostname -F /hostname

if ! mount -t 9p -o trans=virtio host /host; then
    echo 'no host share accessible, it can be added to QEMU using:'
    echo '-virtfs local,path=$(pwd)/,mount_tag=host,security_model=mapped,readonly=off'
fi
if ifconfig -a | grep -q eth0; then
    ifconfig eth0 up
    ifconfig eth0 10.0.2.15 netmask 255.255.255.0 broadcast 10.0.2.255
    route add default gw 10.0.2.2
else
    echo 'no network device'
fi

if [ $# -ge 1 ]; then
    if ! "$@"; then
        echo "command failed: $*"
        sync
        # sleep needed to avoid I/O error
        sleep 0.1
        echo c > /proc/sysrq-trigger
    fi
else
    setsid -c /bin/bash -l || true
fi

sync
# sleep needed to avoid I/O error
sleep 0.1
echo o > /proc/sysrq-trigger
sleep 10
