#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: /path/to/fvp/folder"
    exit 1
fi

if [ "$(which fuse2fs)" == "" ]; then
    echo "fuse2fs must be installed"
    exit 1
fi

if [ "$(which fusermount)" == "" ]; then
    echo "fuse3 must be installed"
    exit 1
fi

set -x

[ -v INIT ] || INIT=/host/guest.sh

fvp_dir=$(readlink -f $1)
if [ ! -f $fvp_dir/FVP_Base_RevC-2xAEMvA ]; then
    echo "error: can't find FVP_Base_RevC-2xAEMvA in $fvp_dir"
    exit 1
fi
export PATH=$fvp_dir:$PATH

FVP_Base_RevC-2xAEMvA --version

cd fvp

pushd rmm
export OUT=${PWD}/../../out
export PATH=${PWD}/../shrinkwrap/shrinkwrap:$PATH
export SHRINKWRAP_CONFIG=${PWD}/tools/shrinkwrap/configs
export WORKSPACE=${PWD}/../
export SHRINKWRAP_BUILD=${WORKSPACE}
export SHRINKWRAP_PACKAGE=${SHRINKWRAP_BUILD}/package

# https://shrinkwrap.docs.arm.com/en/latest/userguide/configstore/cca-3world.html
pushd $WORKSPACE/package/cca-3world/
mkdir -p mnt
cp -f $OUT/host.ext4 host.ext4
cp -f $OUT/guest.ext4 guest.ext4
fuse2fs -o fakeroot host.ext4 mnt
mkdir -p mnt/host/out
cp Image guest.ext4 lkvm mnt/host/out
cp $OUT/../guest.sh mnt/host/
fusermount -u mnt
rm -rf mnt
popd

rootfs=$WORKSPACE/package/cca-3world/host.ext4

# running with runtime=null results in stdout being delayed/absent, thus use
# podman container, but overrides fvp included with latest one.
cat > podman << EOF
#!/usr/bin/env bash
set -euo pipefail
set -x
cmd=\$1; shift
if [ \$cmd == run ]; then
    cmd="\$cmd -v $fvp_dir:/tools/Base_RevC_AEMvA_pkg/models/Linux64_GCC-9.3/"
elif [ \$cmd == exec ]; then
    # dump script to run fvp generated by shrinkwrap 
    if [ -f \${@: -1} ]; then
        cat \${@: -1}
    fi
fi
$(which podman) \$cmd "\$@"
EOF
chmod +x podman

env PATH=./:$PATH \
    shrinkwrap --runtime=podman run cca-3world.yaml --overlay=cca_da.yaml \
    --rtvar ROOTFS=$rootfs \
    --rtvar CMDLINE="nokaslr root=/dev/vda rw init=/init -- $INIT"
