#!/usr/bin/env bash

set -euo pipefail
set -x

export PATH=/usr/bin:/bin:/sbin

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
hostname --file /hostname

mkdir -p /host
mount -t 9p -o trans=virtio host /host
setsid -c -w /usr/bin/bash -l || true

sync
echo o > /proc/sysrq-trigger
sleep 10
